### ISSUE TITLE
Why a DID?

### ISSUE THREAD

**Issue by ra-phael** [Jiliac/verifiable-credential#1]
>In a real application, they would be a Decentralized Identifier (DID) which would point to the keys.
>
>@TODO: why?

Some quick thoughts. 🙂

DIDs offer several advantages, as it’s an identifier:
- It can resolve to multiple public keys
- You can rotate these keys
- It can resolve to service endpoints
- With a pub key there is a risk of impersonation. How can you know for sure the right person controls that key pair? Whereas with a DID the identifier is cryptographically binded to the public key inside the DID document. So if you trust the decentralized identifier (because it's been published in an official registry for example) then you know you can "trust" the public keys associated with it in its DID document.(https://youtu.be/SHuRRaOBMz4?t=3246)

**Comment by Jiliac** [comment]
Awesome. Thanks. Will include it in the text.

> Whereas with a DID the identifier is cryptographically binded to the public key inside the DID document.

I don't understand this part though. In the video you linked, it introduces a "controller" which published both the Public Key and the Identifier. So we are relying on a third party?

**Comment by ra-phael** [comment]
A third party is not necessarily needed as opposed to traditional PKI where you have Certificate Authorities. Here with DIDs you self-certify. If you have a DID registry in a smart contract the number of third parties you rely on is very low.

By controller they mean the person/entity controlling / able to make changes to the DID document.

**Comment by Jiliac** [comment]
> If you have a DID registry in a smart contract the number of third parties you rely on is very low.

Whah ok. Leverage of both worlds capabilities.
